### PR TITLE
Video

### PR DESCRIPTION
**Pull request by some-dude194**
Learn-html.org Video Segment

To embed a youtube video, use the following:
<iframe width="500" height="450" src="https://www.youtube.com/embed/VIDEO-ID-HERE"></iframe>

### CODE REVIEW

**Comment by ronreiter** [comment]
Pretty shocked from this pull request - can we talk over zoom?

**Comment by some-dude194** [comment]
> Pretty shocked from this pull request - can we talk over zoom?

No sorry, but you can contact me at
sparkfiredevelopment@gmail.com

**Comment by some-dude194** [comment]
> Pretty shocked from this pull request - can we talk over zoom?

No sorry, but you can contact me at sparkfiredevelopment@

**Comment by fafmax-xavti1-gUrcit** [comment]
Yes

**Pull request closed without merging**
