### PR TITLE
Header vertical alignment fixes

### PR DESCRIPTION
**Pull request by PeterDavidCarter**
Vertically aligns header logo and social media buttons on a by-domain contextual basis, accounting for variations in logo-size between domains.

### CODE REVIEW

**Comment by ronreiter** [comment]
Thanks for the fix, but the correct way to fix it is to use smarter CSS rules, background image centering or manipulating the images.

**Comment by PeterDavidCarter** [comment]
I did consider image manipulation. Fair enough, if you'd prefer it done that way I'm sure that'd be fine. Out of interest, is your objection to the fix the issue of boilerplate, or something else? I noticed in the list items within the `<ul class="nav nav-pills">` element further down the same HTML page you implemented a solution very similar to mine, though will differing indentation?

As I said, more than will to sort it out with photoshop and a bit of creative image resizing, but I'm curious what the differences are between your solution and mine, and why one is considered best practice.

**Comment by PeterDavidCarter** [comment]
Ok, I've resized all the images using Photoshop so they're not being resized in the browser (faster load times; better image clarify). As requested, all CSS is now smart, in the sense that it is based on templated variables which are in turn pulled from the domain name variables defined in constant.py.

I looked into implementing background image resizing but this solution seems currently optimal and requires slightly less code.

Let me know if you've any more suggestions before merge.

**Comment by PeterDavidCarter** [comment]
Are you going to accept this? I spent 3 hours re-doing this and running through the C tutorials with a misaligned banner logo is very off-putting.

**Comment by ronreiter** [comment]
Sorry for dragging you. I will review this soon.

**Comment by ronreiter** [comment]
Hi @PeterDavidCarter,
Sorry for the late reply, but I think this is no longer relevant. I did a revamp of the design.
Please let me know if you'd like to review this again and help me with improving the design even further!

**Pull request closed without merging**
