### PR TITLE
Added separate Class Variables.md to introduce fields and updated Class Properties.md to introduce C# properties

### PR DESCRIPTION
**Pull request by rickhaws**
C# has separate constructs "fields" and "properties."  Fields are regular class variables, while properties wrap fields with get and set accessors. Separated the two concepts into two different sections.

### CODE REVIEW

**Comment by ronreiter** [comment]
Hey @rickhaws - can you check the conflicts and see how you can update the pull request so the merge will be possible easily?
Thanks

**Comment by rickhaws** [comment]
Sure.  I was just wondering yesterday how the pull request was doing.
Hopefully I can get to that today.

**Comment by rickhaws** [comment]
@ronreiter, I finally came to look at the merge conflicts, and it looks like there aren't any conflicts anymore.  Can you look to verify that for me?  If there aren't any then it should be ready for merge.  If there are still conflicts, I'll need help seeing them as I'm still not proficient in the GitHub interface.

**Comment by rickhaws** [comment]
Ron,

I don't know if you saw my reply, but it looks like there aren't any
conflicts.  Let me know if I'm missing anything or if I can help.

-Rick

**Comment by rickhaws** [comment]
I think this is ready to be merged.  Please let me know if there is anything else to do

**Pull request closed without merging**
