### PR TITLE
Perl: fixed all modules

### PR DESCRIPTION
**Pull request by miparnisari**
Sorry for the long PR! I started to go through the live tutorial, saw that it was riddled with errors and decided to fix them all.

- Fixed all the errors I found, including formatting, grammar, typos
- Fixed some broken solutions for exercises
- Added relevant information, including scoped variables, boolean data types, etc
- Added exercises where they were missing 
- Added missing solution exercises. 

I tested every page and removed some files that were duplicate.

I'm still missing an exercise for the "references" module.

### CODE REVIEW

**Comment by miparnisari** [comment]
@ronreiter can you have a look?

**Comment by ronreiter** [comment]
Thanks! I am reviewing. It's a big one...

**Comment by miparnisari** [comment]
I think it will be easier if you grab the changes and view them live on the site.

**Comment by bashedpotato** [comment]
i can review it only on next wed thu
 

    On Thursday, December 14, 2017, 4:53:04 AM GMT+2, Ron Reiter <notifications@github.com> wrote:  
 
 
Thanks! I am reviewing. It's a big one...

**Comment by miparnisari** [comment]
Any comments?

**Comment by miparnisari** [comment]
@ronreiter @bashedpotato any updates?

**Comment by miparnisari** [comment]
Guys? Can you please review it? @ronreiter @bashedpotato

**Comment by ronreiter** [comment]
Thanks @miparnisari!

**Pull request merged**
