### PR TITLE
fixed  #60

### PR DESCRIPTION
**Pull request by TarangVerma**
updated  manipulating arrays.md
thank you!❤️

### CODE REVIEW

**Comment by TarangVerma** [comment]
I will be very happy if you merge this in your main file

**Comment by ronreiter** [comment]
But your code is wrong, did you check it?

**Comment by TarangVerma** [comment]
Screenshot (2)
I think here it will be 7 instead of 5.

**Comment by ronreiter** [comment]
As I said, you are wrong. And you can easily test it. So why are you trying
to send a fix if you didn't even try the code suggestion?

- Ron

**Pull request closed without merging**
